version: '3.8'
services:
  db:
    build: ./db
    # restart: always
    environment:
      POSTGRES_USER: bikeapp
      POSTGRES_PASSWORD: bikeapp
      POSTGRES_DB: bikeapp
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/csvs
  # adminer:
  #   image: adminer:4.8.1
  #   restart: always
  #   ports:
  #     - 8088:8080