version: '3.8'
services:
  api:
    container_name: "api"
    build: ./backend
    ports:
      - '3002:80'
    links:
      - "db"
  db:
    build: ./db
    container_name: "db"
    environment:
      POSTGRES_USER: bikeapp
      POSTGRES_PASSWORD: bikeapp
      POSTGRES_DB: bikeapp
    ports:
      - '5432:5432'
  client: 
    build: ./frontend
    container_name: "frontend"
    links:
      - "api"
    # expose:
    #   - 80
    ports:
      - "3001:80"
  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "80:80"
  #   container_name: "production_nginx"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #   links:
  #     - "api"
  #     - "client"