version: '3.8'
services:
  # backend:
    # restart: on-failure
    # build: 
    #   dockerfile: ./backend/Dockerfile
    # links:
    #   - db
    # ports:
    #   - '3003:8000'
    # volumes:
    #   - /data
    #   - ./:/usr/src/app/
    #   - /usr/src/app/node_modules
    # depends_on:
    #   - db
  db:
    build: ./db
    container_name: "db"
    environment:
      POSTGRES_USER: bikeapp
      POSTGRES_PASSWORD: bikeapp
      POSTGRES_DB: bikeapp
    ports:
      - '5432:5432'
