version: '3.8'
services:
  db:
    build: ./db
    container_name: "db"
    environment:
      POSTGRES_USER: bikeapp
      POSTGRES_PASSWORD: bikeapp
      POSTGRES_DB: bikeapp
    ports:
      - '5432:5432'