name: Node.js CI

on: push
    
jobs:
  TestFrontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    - name: Test frontend
      run: |
        npm ci
        npm run build --if-present
        npm run lint
        npm run check-format
        npm run format
        npm test
    - name: Get commit hash
      if: ${{ always() }}
      run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
      id: slug
    - name: Chat Setup
      if: ${{ always() }}
      uses: DTherHtun/google-chat-action@v0.8
      with:
        project: ${{ github.repository }}
        commit: ${{ steps.slug.outputs.sha8 }}
        branch: 'Frontend'
        status: ${{ job.status }}
        actionid: ${{ github.repository }}/runs/${{ github.run_id }}
        webhook: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}

  TestBackend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json
    - name: Test backend
      run: |
        npm ci
        npm run build --if-present
        npm run lint
        npm run format
    - name: Get commit hash
      if: ${{ always() }}
      run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
      id: slug
    - name: Chat Setup
      if: ${{ always() }}
      uses: DTherHtun/google-chat-action@v0.8
      with:
        project: ${{ github.repository }}
        commit: ${{ steps.slug.outputs.sha8 }}
        branch: 'Backend'
        status: ${{ job.status }}
        actionid: ${{ github.repository }}/runs/${{ github.run_id }}
        webhook: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}