name: Node.js CI

on: push
    
jobs:
  TestFrontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    - name: Google Chat Notification
        run: |
          curl --location --request POST '${{ secrets.GOOGLE_CHAT_WEBHOOK }}' \
          --header 'Content-Type: application/json' \
          --data-raw '{
              "cards": [
                  {
                      "header": {
                          "title": "Issue Tracker",
                          "subtitle": "Issue No: #${{ github.event.issue.number }}"
                      },
                      "sections": [
                          {
                              "widgets": [
                                  {
                                     "keyValue": {
                                          "topLabel": "Creator",
                                          "content": "${{ github.event.issue.user.login }}"
                                      },
                                   },
                                   {
                                     "keyValue": {
                                          "topLabel": "Title",
                                          "content": "${{ github.event.issue.title }}"
                                      }
                                   },
                                   {
                                     "keyValue": {
                                          "topLabel": "Assigned Lables",
                                          "content": "- ${{ join(github.event.issue.labels.*.name) }}"
                                      }
                                   },
                                   {
                                     "keyValue": {
                                          "topLabel": "Assignees",
                                          "content": "- ${{ join(github.event.issue.assignees.*.login) }}"
                                      }
                                   },
                                   {
                                      "buttons": [
                                          {
                                              "textButton": {
                                                  "text": "OPEN ISSUE",
                                                  "onClick": {
                                                      "openLink": {
                                                          "url": "${{ github.event.issue.html_url }}"
                                                      }
                                                  }
                                              }
                                          }
                                      ]
                                  }
                              ]
                          }
                      ]
                  }
              ]
          }'
          if: always()
    - name: Test frontend
      run: |
        npm ci
        npm run build --if-present
        npm run lint
        npm run check-format
        npm run format
        npm test

  TestBackend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json
    - name: Test backend
      run: |
        npm ci
        npm run build --if-present
        npm run lint
        npm run format
